### ISSUE TITLE
Docker build breaks with update for 2.26.0/2.25.0: "error: unknown option '-o'"

### ISSUE THREAD

**Issue by JSteeleAZ** [felt/tippecanoe#101]
Docker build process that was working on May 8, 2023 using v2.24.0 are not functioning with 2.26/2.25. 

Environment:
Win10 Pro, build: 19044.2846
Docker Desktop, engine: 20.10.23

I am using a dummy container to create a volume to share the input and output files:

![image](https://github.com/felt/tippecanoe/assets/4723429/9bb7e165-b150-492e-b20d-ecafce0febd1)
Observe the file in.geojson is available in the volume:

![image](https://github.com/felt/tippecanoe/assets/4723429/83dbd3f7-0705-463c-873d-2605bc9a3d11)

Execute docker build (as described in the readme, and was working with v.2.24.0), and observe no issues:

![image](https://github.com/felt/tippecanoe/assets/4723429/4dd07a81-beb8-4b03-95c3-bcc1a3ba9337)

I had previously discovered that the example "run" command in the readme was incorrect. 
The following version worked for me:

```
docker run -it --rm -v data:/data felt/tippecanoe:latest tippecanoe -o /data/out.mbtiles /data/in.geojson
```

When this command started failing with v2.25/2.26, I attempted the following versions inspired from the readme:
```
docker run -it --rm -v data:/data felt/tippecanoe:latest tippecanoe --output=/data/out.mbtiles /data/in.geojson
docker run -it --rm -v /data:/data felt/tippecanoe:latest tippecanoe --output=/data/out.mbtiles /data/in.geojson
```

Observe the following errors for the 3 versions of "run":
```
PS C:\REPOS\TileServerLocal> docker run -it --rm -v data:/data felt/tippecanoe:latest tippecanoe -o /data/out.mbtiles /data/in.geojson
error: unknown option '-o'
PS C:\REPOS\TileServerLocal> docker run -it --rm -v data:/data felt/tippecanoe:latest tippecanoe --output=/data/out.mbtiles /data/in.geojson
error: unknown option '--output=/data/out.mbtiles'
PS C:\REPOS\TileServerLocal> docker run -it --rm -v /data:/data felt/tippecanoe:latest tippecanoe --output=/data/out.mbtiles /data/in.geojson
error: unknown option '--output=/data/out.mbtiles'
```
![image](https://github.com/felt/tippecanoe/assets/4723429/7837ed6f-8c24-4905-aa7a-8f669bcb8d57)

I also receive the unknown option error when setting "Z" and "z" options.

Sample input file attached, but renamed to "txt" for upload:
[in.txt](https://github.com/felt/tippecanoe/files/11435092/in.txt)

**Comment by jtmiclat** [comment]
Hi @JSteeleAZ , I updated the dockerfile in the following PR #79.  Based on your logs, you aren't referring to the [dockerfile ](https://github.com/felt/tippecanoe/blob/main/Dockerfile)of tippecanoe though as you are using a different dockerfile/repository. Would it be possible for you to post the dockerfile you are using to build tippecanoe and maybe i can help?

**Comment by JSteeleAZ** [comment]
Thank you for taking a look @jtmiclat!

You're correct, I was referring to a different version of ```Dockerfile``` in my directory "TileServerLocal". Running against a fresh clone worked perfectly. Copying the results here for completeness.

Thank you very much.

![image](https://github.com/felt/tippecanoe/assets/4723429/5193e61d-2e75-4edc-9960-4c8d789950d5)
