### ISSUE TITLE
How to allow tippecanoe to use higher server resources.

### ISSUE THREAD

**Issue by DeepakSharda** [felt/tippecanoe#140]
While buidling tiles for a country at zoom level 18 it takes lot of time as if there is an option to allow to use more server power on linux so to speed up the process ?

**Comment by e-n-f** [comment]
Tippecanoe will already try to use as many processing threads as are available. Please make sure you are writing to an mbtiles file with `-o` instead of a directory of files with `-e`, since creating new files can be a significant fraction of processing time.
