### ISSUE TITLE
Issue while using overzoom.

### ISSUE THREAD

**Issue by DeepakSharda** [felt/tippecanoe#141]
we tried making tile join with version 2.3.1  like 

it works 
tile-join -z16 -Z0  -o /var/merged/'.$filename.'/'.$filename.'.mbtiles  -pk -pg';

it doesnt work 

tile-join -z16 -Z0  -o /var/merged/'.$filename.'/'.$filename.'.mbtiles --overzoom -pk -pg';

We have two line layers one with zoom level 16 and other with zoom level 19.  trying to use tile join where we can get the layer with zoom 16 to get overzoomed to zoom 19 in merged tiles.

**Comment by e-n-f** [comment]
There were some bad performance problems with `--overzoom` that should be better after https://github.com/felt/tippecanoe/pull/149 and https://github.com/felt/tippecanoe/pull/147. Could you try it again and see if it works better for you now?

**Comment by DeepakSharda** [comment]
It works. Fixed the issue. Thanks a lot for your help
