### ISSUE TITLE
Update PMTiles metadata

### ISSUE THREAD

**Issue by dvd3v** [felt/tippecanoe#145]
It seems it's not possible to easily update the metadata of a PMTiles file using the `-n`, `-N` and `-A` flags. It is possible to use `tile-join` and create a copy of the dataset with updated metadata, but this is not efficient since it will then need to decode and re-encode all features. Also, the sqlite3 approach as suggested [here](https://github.com/mapbox/tippecanoe/issues/758) does not work for PMTiles.

Any suggestions?

**Comment by bdon** [comment]
This wouldn't belong in tippecanoe, I have an open issue for this in the pmtiles cli here: https://github.com/protomaps/go-pmtiles/issues/63

would that be a viable solution?

**Comment by dvd3v** [comment]
Yes, that would be a good solution. Thanks for pointing it out, I will close this issue.

**Comment by dvd3v** [comment]
Yes, that would be a good solution. Thanks for pointing it out, I will close this issue.
