### ISSUE TITLE
PMTiles file generated from FlatGeobuf has wrong boolean value

### ISSUE THREAD

**Issue by Danysan1** [felt/tippecanoe#180]
I have a flatgeobuf file which contains some boolean properties for each feature, each with some true values and some false values. For example:
![Screenshot 2023-12-16 194346](https://github.com/felt/tippecanoe/assets/8406735/5b05e821-2d23-4b0b-9674-d7136ea6568e)

[Link to the fgb file](https://etymology-it.dsantini.it/etymology_map.fgb)

I tried multiple times generating a pmtiles file with tippecanoe 2.35.0:
```sh
tippecanoe 'etymology_map.fgb' --output='etymology_map.pmtiles' --layer=etymology_map -Z 13 -z 13 -f
```

The file is generated with all the values in these columns as false. For example, the element shown above can be inspected with the pmtiles inspector at [this link](https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fetymology-it.dsantini.it%2Fetymology_map.pmtiles#map=13.15/45.91079/12.16873):
![Screenshot 2023-12-16 155431](https://github.com/felt/tippecanoe/assets/8406735/3c07cf8d-fedb-464e-95c9-78231e65d1c6)

[Link to the pmtiles file](https://etymology-it.dsantini.it/etymology_map.pmtiles)

Boolean values should be carried intact from the source file to the generated file

**Comment by bdon** [comment]
this is likely a bug in the FlatGeobuf-specific data parsing, thanks for reporting.

**Comment by Danysan1** [comment]
FYI I replaced the pmtiles linked above so it's not a good example anymore. Anyway, I didn't replace the .fgb so it can still be used as example
