### ISSUE TITLE
building_polygon creation at higher ZOOM slab is not working 

### ISSUE THREAD

**Issue by DeepakSharda** [felt/tippecanoe#259]
this works 

tippecanoe -Z14 -z20 -l building_polygon --drop-densest-as-needed --detect-shared-borders --coalesce-densest-as-needed -o /mnt/building_polygon_5.mbtiles /mnt/geojson_files/table_1.geojson --force

this doesnt 
tippecanoe -Z17 -z20 -l building_polygon --drop-densest-as-needed --detect-shared-borders --coalesce-densest-as-needed -o /mnt/building_polygon_5.mbtiles /mnt/geojson_files/table_1.geojson --force

no change in data all the zoom below 14 works all the zoom above 14 doesn't.

data is geoparquet from overture converted into geojson with id and geom column only.

**Comment by DeepakSharda** [comment]
sorry issue resolved it was a mistake .

**Comment by e-n-f** [comment]
Glad you figured it out!
