### ISSUE TITLE
Feature request: `--drop-by-lowest-value`

### ISSUE THREAD

**Issue by Robinlovelace** [felt/tippecanoe#288]
Currently the docs recommend `--drop-densest-as-needed` to enable visualisation of large datasets, but sometimes there's information in the attributes that can determine which features are more important and therefore which should be kept.

Would it be possible to have such a feature?

Apologies if there's a way to do this already that I haven't picked up from the docs, have had a read, and we have done a few tests and a fair amount of discussion. Context: https://github.com/nptscot/nptscot.github.io/issues/258

**Comment by amandasaurus** [comment]
Sounds like #132, a feature I would also love!

**Comment by Robinlovelace** [comment]
Closing in favour of that one.
