### ISSUE TITLE
A float attribution for a point is being completely changed

### ISSUE THREAD

**Issue by amandasaurus** [felt/tippecanoe#291]
I have a collection of points in a GeoJSONSeq file, each has a `nid`, `upstream_m` and optionally other values. But `tippecanoe` is turning the `upstream_m` value into some wild value (multiplying by about 8 million).

e.g., download `[planet-ends.geojsons.zstd`](https://data.waterwaymap.org/2024-11-06-tippecanoe-attribute-changed/planet-ends.geojsons.zst) _(50 MiB)_, unzip it, and run:

    tippecanoe  -o planet-ends.pmtiles planet-ends.geojsons --drop-smallest-as-needed -z 10
 
One of the features (with `nid = 12003214081`) has it's `upstream_m` value changed from `1395.9` to `11650524360`.

In the input geojsons, it's `"upstream_m":1395.9`:

    $ grep 12003214081 planet-ends.geojsons
     {"properties":{"nid":12003214081,"upstream_m":1395.9}, "geometry": {"type":"Point", "coordinates": [26.158626, 46.266276]}, "type": "Feature"}

But the output pmtiles has `"upstream_m": 11650524360`:

    $ tippecanoe-decode planet-ends.pmtiles 10 586 363 | grep 12003214081
    { "type": "Feature", "properties": { "nid": 12003214081, "upstream_m": 11650524360 }, "geometry": { "type": "Point", "coordinates": [ 26.158619, 46.266291 ] } }

The same result happens with mbtiles output, instead of pmtiles.

(These are the point data created for [WaterwayMap.org/ends](https://waterwaymap.org/ends) if you wanna see it in the real world)

Changing that attribute by such a wild amount is a bug. 😉

I've seen a few other examples of wildly inflated attributes in that dataset, but >99% appear correct.

tippecanoe v2.52.0 running on Ubuntu Debian 12 bookworm. I've run it many times with the same results.

**Comment by e-n-f** [comment]
Glad to hear that upgrading fixed it!
