### ISSUE TITLE
`--feature-filter` type conversion

### ISSUE THREAD

**Issue by sietsevanderbom** [felt/tippecanoe#295]
The [issue](https://github.com/mapbox/tippecanoe/issues/893) appears to be that if the field is last, it does not convert it to the proper type.
```
These two filters work with no problems:
--feature-filter='{ "*": [ "any", [ ">=", "show_at_zoom", 5 ] ] }'
--feature-filter='{ "*": [ "any", [ ">=", "$zoom", 5 ] ] }'

However, this does not work and gives the mismatch error:
--feature-filter='{ "*": [ "any", [ ">=", "$zoom", "show_at_zoom" ] ] }'

These two filters do not work, either, and give a "!has" key is not a string error.
--feature-filter='{ "*": [ "any", [ ">=", 5, "$zoom" ] ] }'
--feature-filter='{ "*": [ "any", [ ">=", 5, "show_at_zoom" ] ] }'
```

I'd really think we would need to be able to do this:
```
--feature-filter=`{"my_layer":["all", [">=","$zoom","minzoom"],["<=","$zoom","maxzoom"]]}'
```

As that doesn't work I hack around this now with something like:
```
--feature-filter='{"my_layer":["any",["all",[">=","minzoom",2],[">=","$zoom",2],["<=","$zoom",3],["<=","maxzoom",3]],["all",[">=","minzoom",4],[">=","$zoom",4],["<=","$zoom",5],["<=","maxzoom",5]],["all",[">=","minzoom",6],[">=","$zoom",6],["<=","$zoom",7],["<=","maxzoom",7]],["all",[">=","minzoom",8],[">=","$zoom",8],["<=","$zoom",9],["<=","maxzoom",9]],["all",[">=","minzoom",10],[">=","$zoom",10],["<=","$zoom",11],["<=","maxzoom",11]]]}'
```
but it forces me to cut things up into 'zoomlayers' and still doesn't give me the same.  E.g. it would not include an item with minzoom 2 and maxzoom 11 (and many other items that are not sliced up into my 'hackzoomlayers').

**Comment by e-n-f** [comment]
This is the unfortunate result of the [old "other filter" spec](https://docs.mapbox.com/style-spec/reference/other/#other-filters) that Tippecanoe's filters implement: the first argument to a comparison is always an attribute name, and the second argument is always a literal value.

The recent filter work in Tippecanoe has been to support an entirely different filter syntax used within Felt, which unfortunately has a similar limitation.

I agree it would be better to support a more general filter syntax like the current Mapbox GL expressions, but can't currently justify that development effort.
