### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by magna25** [felt/tippecanoe#65]
```
git clone https://github.com/felt/tippecanoe.git
cd tippecanoe
docker build -t tc .
```
getting:
```
#10 15.21 projection.cpp: In function 'void lonlat2tile(double, double, int, long long int*, long long int*)':
#10 15.21 projection.cpp:25:32: error: 'fpclassify' was not declared in this scope
#10 15.21   int lat_class = fpclassify(lat);
#10 15.21                                 ^
#10 15.21 projection.cpp:25:32: note: suggested alternative:
#10 15.21 In file included from projection.cpp:5:0:
#10 15.21 /usr/include/c++/5/cmath:581:5: note:   'std::fpclassify'
#10 15.21      fpclassify(_Tp __x)
#10 15.21      ^
#10 15.21 projection.cpp: In function 'void epsg3857totile(double, double, int, long long int*, long long int*)':
#10 15.21 projection.cpp:77:30: error: 'fpclassify' was not declared in this scope
#10 15.21   int iy_class = fpclassify(iy);
#10 15.21                               ^
#10 15.21 projection.cpp:77:30: note: suggested alternative:
#10 15.21 In file included from projection.cpp:5:0:
#10 15.21 /usr/include/c++/5/cmath:581:5: note:   'std::fpclassify'
#10 15.21      fpclassify(_Tp __x)
#10 15.21      ^
#10 15.21 Makefile:74: recipe for target 'projection.o' failed
#10 15.21 make: *** [projection.o] Error 1
------
executor failed running [/bin/sh -c make   && make install]: exit code: 2
```

**Comment by jtmiclat** [comment]
@magna25 I have a working docker file for tippecanoe you can use! The dockerfile for tippecanoe hasn't been updated in forever so I am not sure if there is an interest to maintain it.

https://github.com/jtmiclat/tippecanoe-docker/blob/master/Dockerfile

**Comment by traviskirstine** [comment]
@jtmiclat Thanks for the docker file, it worked for me but the tile-join application wasn't installed - any ideas? 

 docker run -it --rm -v `pwd`:/data tippecanoe:latest tile-join
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "tile-join": executable file not found in $PATH: unknown.

**Comment by traviskirstine** [comment]
@jtmiclat added the following line to copy the tile-join executable to the bin directory and rebuilt the image - it now works - Thanks

COPY --from=tippacanoe-builder /tmp/tippecanoe-src/tile-join /usr/local/bin/

**Comment by jtmiclat** [comment]
@traviskirstine Thanks for catching updated my docker image!
