### ISSUE TITLE
Installation instructions / Homebrew

### ISSUE THREAD

**Issue by tordans** [felt/tippecanoe#70]
I am not familiar with `make` and cannot get the installation instructions running https://github.com/felt/tippecanoe#installation.
Is there a way to get a packaged version on Homebrew [like the mapbox instructions](https://github.com/mapbox/tippecanoe#installation)? Maybe under a new name like "felt-tippecanoe"?

Or, alternatively some Github Action that will create a realease hier in Github to be downloaded?

---

Update: The docker image looked like the best bet to get this running more easily https://github.com/felt/tippecanoe#docker-image. However, I ran into issues with `docker: Error response from daemon: error while creating mount source path '/host_mnt/tiledata': mkdir /host_mnt/tiledata: input/output error.` — Did not investigate this further.

**Comment by bdon** [comment]
Homebrew already points to this repo: https://formulae.brew.sh/formula/tippecanoe

**Comment by tordans** [comment]
Thanks @bdon. Ideally, we would update the README here and send a PR to the Mapbox version since that has now the wrong info (it suggests that the Mapbox version is being installed).

I might find time to do both, but anyone feel free to do it first :)

**Comment by bdon** [comment]
A README update here would be welcome. AFAIK no-one actively working on tippecanoe has commit access to the mapbox version, however.

**Comment by jasonferrier** [comment]
This issue can be closed as Homebrew switched over to this project back on 2022-Oct-17: Homebrew/homebrew-core@e02b07c30a47f04068536b3af70106c4b11ca14a, thanks to @e-n-f !

**Comment by jasonferrier** [comment]
I have created a PR that adds the Homebrew installation instructions for this project. #130
