### ISSUE TITLE
Check before starting work on option for brotli compression

### ISSUE THREAD

**Issue by tomeronen** [felt/tippecanoe#76]
Hello, wanted to try and add option for `brotli` compression, But first wanted to check if this is even a wanted feature.

**Comment by bdon** [comment]
@tomeronen thanks for the inquiry! What program do you plan to use to read a Brotli-compressed archive? I think the practicality of this option will depend on there being other tools in the ecosystem that support it.

**Comment by tomeronen** [comment]
My specific use case is creating tiles in fie directory and pmtiles using tippecanoe and then serving them to be rendered on the clients map in a web browser.

**Comment by bdon** [comment]
The pmtiles client can only support Gzip compression right now; it's not practical to add Brotli because of performance and bundle size. In the future when all browsers support DecompressionStream with `br` encoding this should be a very worthwhile enhancement (right now only Chrome does)

**Comment by tomeronen** [comment]
makes sense :) thanks for the response
