### ISSUE TITLE
QGIS can't read tiles output to directory

### ISSUE THREAD

**Issue by rbrtmrtn** [felt/tippecanoe#85]
Hello, and thank you for this tool which was been so helpful to me over the years!

I am trying to convert a GeoJSON file to a directory of tiles. This is the command I'm using:

```
tippecanoe -zg --drop-densest-as-needed -e ~/summary_hexagons ~/summary_hexagons.geojson 
```

The command seems to run fine:

```bash
For layer 0, using name "summary_hexagons"
120038 features, 11964453 bytes of geometry, 2041151 bytes of string pool
Choosing a maxzoom of -z6 for features typically 3791 feet (1156 meters) apart, and at least 1893 feet (577 meters) apart
tile 4/4/5 size is 501839 with detail 12, >500000    
Going to try keeping the sparsest 89.67% of the features to make it fit
tile 4/4/6 size is 668613 with detail 12, >500000    
[truncated for brevity]
  99.9%  6/18/24  
```

Next, I try viewing these in QGIS. No geometries appear on the map and if I try adding a random `.pbf` from the output directories, I get an error `Invalid Data Source: /Users/me/summary_hexagons/1/0/0.pbf is not a valid or recognized data source`.

If I inspect one of the `.pbf`s in the [Protobuf Viewer](https://apps.apple.com/us/app/protobuf-viewer/id1165908879?mt=12) macOS app, I'm not seeing a valid structure. I'm not a protobuf expert, but when I've used this app with valid tiles I usually see a tree-like structure. This just has a top-level `Root` with no apparent contents.

If I switch from `tippecanoe -e ~/summary_hexagons` to `-o summary_hexagons.mbtiles` it works fine, and I can view the tiles successfully in QGIS. I can also view the source GeoJSON in QGIS without issue.

Is there something specific to the `-e` flag I might be doing wrong here? I hope this is enough information to go on, and thanks so much in advance for any pointers!

**Comment by mtravis** [comment]
I think the issue maybe that GDAL, and therefore QGIS can't parse the pbf. I only ever use the mbtiles to view the output of tippecanoe in QGIS.

**Comment by rbrtmrtn** [comment]
Thanks @mtravis , that makes sense it could be a GDAL issue. These are ultimately going into a MapboxGL web app, so I'll try pulling them into the app next. Normally I do a quick sanity check by viewing them in QGIS first, but it sounds like this might not be possible.

**Comment by rbrtmrtn** [comment]
I did a few things to get this working and I believe the culprit was ultimately GZIP compression. QGIS didn't like the compressed tiles. Running it again with `-pC` did the trick!
