### ISSUE TITLE
Other input formats?

### ISSUE THREAD

**Issue by Robinlovelace** [felt/tippecanoe#90]
.geojson files can get huge and a bit unwieldy. 

Wondering if at some point it would be in scope for `tippecanoe` to accept more space efficient formats like GeoPackage or the under-development GeoArrow spec: https://github.com/geoarrow/geoarrow

Reading [this](https://github.com/felt/tippecanoe/issues/57) by @bdon and chatting with @dabreegster about performance got me wondering...

**Comment by Robinlovelace** [comment]
Update, I see that it supports GeoBuff files, meaning many of advantages of .gpkg binary format: https://github.com/felt/tippecanoe/tree/main/flatgeobuf

I see .gpkg and other formats as a nice-to-have, and just wondering if it's in the roadmap.

**Comment by bdon** [comment]
do you have `ogr2ogr` installed? You should be able to stream any file format `ogr2ogr` can read into GeoJsonSeq input for tippecanoe. I believe that's a more complete solution than adding every file format to tippecanoe itself.

**Comment by Robinlovelace** [comment]
> do you have `ogr2ogr` installed? You should be able to stream any file format `ogr2ogr` can read into GeoJsonSeq input for tippecanoe. I believe that's a more complete solution than adding every file format to tippecanoe itself.

I do and agreed, no point in reinventing wheels here. Thanks!
