### ISSUE TITLE
Segmentation Fault Processing Large GeoJSON (>100 GB)

### ISSUE THREAD

**Issue by diehl** [felt/tippecanoe#96]
I polygonized the National Land Cover Database (https://www.mrlc.gov/data/nlcd-2019-land-cover-conus) in QGIS and am attempting to build vector tiles from the resulting GeoJSON which is 129 GB. Running the following is producing a segmentation fault. Am I pushing beyond the bounds of what tippecanoe can handle? Or are there other pathways I should explore? Any pointers would be greatly appreciated!

```
tippecanoe -z10 -o nlcd_2019_land_cover_l48_20210604.mbtiles nlcd_2019_land_cover_l48_20210604.geojson
For layer 0, using name "nlcd_2019_land_cover_l48_20210604"
zsh: segmentation fault  tippecanoe -z10 -o nlcd_2019_land_cover_l48_20210604.mbtiles
```

**Comment by mtravis** [comment]
Try exporting the Flatgeobuf instead, that should roughly half the size of the file. Flatgeobufs are also quicker to run in tippecanoe.

**Comment by mtravis** [comment]
You could try exporting as a flatgeobuf instead. The file should be half the size then.

**Comment by diehl** [comment]
@mtravis Thanks Matt! I'll give this is a shot.

**Comment by diehl** [comment]
@mtravis I just attempted to run tippecanoe on the Flatgeobuf version of the data and surprisingly enough, it segfaulted immediately. 

```
% tippecanoe -z10 -o nlcd_2019_land_cover_l48_20210604.mbtiles nlcd_2019_land_cover_l48_20210604.fgb
For layer 0, using name "nlcd_2019_land_cover_l48_20210604fgb"
detected indexed FlatGeobuf: assigning feature IDs by sequence
zsh: segmentation fault  tippecanoe -z10 -o nlcd_2019_land_cover_l48_20210604.mbtiles
```

**Comment by mtravis** [comment]
Have you tried exporting a small subset of the data (around 10%) and see if you get an error still?

**Comment by diehl** [comment]
Great idea. I'll do that and report back.

**Comment by diehl** [comment]
This test is exposing more questions about what QGIS is producing. Going to close this thread as the issue might very well be farther upstream. Thanks for the feedback @mtravis - much appreciated!
